<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IV.ManagementHub.Common\IV.ManagementHub.Common.csproj" />
    <ProjectReference Include="..\IV.ManagementHub.ServiceDefaults\IV.ManagementHub.ServiceDefaults.csproj" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
        <PackageReference Include="IV.DX" Version="0.246.0" />\n        <PackageReference Include="IV.DX.Presentation" Version="0.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Migration\Scripts\01_01_0013_MH_DXNavigationItemUnits.dx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Migration\Scripts\01_01_0012_MH_DXDataSetViewUnits.dx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Migration\Scripts\01_01_0002_MH_DXUnitDefinitionUnit.dx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Migration\Scripts\01_01_0001_MH_DXUnitDefinitionUnit.dx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Migration\Scripts\01_01_0010_MH_DXQueryUnits.dx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>

