<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\IV.DX.ManagementHub.Common\IV.DX.ManagementHub.Common.csproj" />
        <ProjectReference Include="..\IV.DX.ManagementHub.ApiService\IV.DX.ManagementHub.ApiService.csproj" />
        <PackageReference Include="IV.DX" Version="0.265.0" />
        <PackageReference Include="IV.DX.Presentation" Version="0.39.0" />
        <PackageReference Include="IV.DX.WebApi" Version="0.19.0" />
        <PackageReference Include="IV.DX.WebApi.Auth" Version="0.4.0" />
        <PackageReference Include="IV.DX.WebApi.Management" Version="0.6.0" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.12.1" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.12.1" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.10" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <TypeScriptCompile Include="wwwroot\scripts.js" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="MigrationScripts\ManagementHub.json" />
      <EmbeddedResource Include="MigrationScripts\ManagementHub\**\*.dx" />
    </ItemGroup>
</Project>
